### PR TITLE
fix(costmodels): on submit click on the 'Next' button in the wizard

### LINKED ISSUE #1105: On clicking enter in text input the create cost model wizard reloads the page
**Describe the bug**
On creating a cost model through the wizard when choosing a text input and pressing Enter the wizard disappears and it looks like the cost models page is refreshing.

**To Reproduce**
1. Go to 'cost model details'
2. Click on 'Create a cost model'
3. Focus on the Name field
4. Click Enter
5. See error

**Expected behavior**
When being on a text input and clicking Enter, click on the Next button to move to the next step if it's enabled.

### PR DESCRIPTION
**Pull request by boaz0**
closes #1105

### CODE REVIEW

File: src/components/forms/form.tsx [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+import { Omit } from 'react-redux';
+
+type FormProps = Omit<FormPF4Props, 'onSubmit'>;
+
+const ignoreSubmit = (event: React.FormEvent<HTMLFormElement>) => {
+  event.preventDefault();
+  const submitButton = document.querySelector(
+    'button.pf-m-primary[type="submit"]'
+  ) as HTMLButtonElement;
+  submitButton.click();
```
Comment (dlabrecq) [inline src/components/forms/form.tsx]: This makes the assumption that every form will have a button that matches the class 'button.pf-m-primary[type="submit"]'. Instead of making an assumption that button exists, it would be preferable to have the button's onClick call `preventDefault`.

For example, in ocpDetails/detailsTag.tsx, I do this in the button's onClick function.

```
public handleOpen = event => {
    this.setState({ isOpen: true });
    event.preventDefault();
    return false;
  };
```

And in azureDataSource/index.tsx, azureCreds/index.tsx, etc. I see that you have been doing this:

```
<Form
      onSubmit={e => {
        e.preventDefault();
        return false;
      }}
    >
```

Comment (boaz0) [reply src/components/forms/form.tsx]: I am not sure I understood what you were saying.
If I'm not wrong when you're pressing Enter in the input box, it triggers the "submit" event.
Although I agree with you that I'm doing here a bad assumption, I don't think calling preventDefault from the onClick button will fix it. Did you try it?

Comment (boaz0) [reply src/components/forms/form.tsx]: In addition, the requirement was to click on the Next button on pressing enter on the input box so I'm not sure how that works.

Comment (boaz0) [reply src/components/forms/form.tsx]: Intresting....

Comment (boaz0) [reply src/components/forms/form.tsx]: Unfortunately, in the wizard I can not set the "onClick" props of the buttons.
Nevertheless, even if it was possible, the problem was pressing enter when you're on the input box. But going to every text input and adding `onClick={e => e.preventDefault()}` doesn't sound so good.

I do understand that I'm doing an assumption of having the submit button. So what I can do is move this to `createCostModelWizard` instead putting it in `components`

Comment (dlabrecq) [reply src/components/forms/form.tsx]: Pressing enter in the input box shouldn’t navigate the user to the next step. (Perhaps set focus on the button?) The user shouldn’t navigate elsewhere unless they click on the next button. Is that what’s happening?

Comment (boaz0) [reply src/components/forms/form.tsx]: there is a conflict then. @nlcwong - in the fit & finish I remembered you mentioning on pressing enter in the input box was to move to the next button

image

Comment (dlabrecq) [reply src/components/forms/form.tsx]: Looking at the PatternFly wizard example and the text input does not navigate the user to the next step. Although, that could be a PatternFly issue?

Comment (nlcwong) [reply src/components/forms/form.tsx]: What i wrote on the box is the issue.  It's not supposed to behave that way.  When a user clicks the "Enter" key, it should not auto-advance the step UNLESS the focus is on the primary button.  If the focus is on the primary button, wouldn't any key then make the button depress and do that action?

Comment (boaz0) [reply src/components/forms/form.tsx]: OK thanks.

**Comment by boaz0** [comment]
ping @dlabrecq can you review this now?
