### PR TITLE
fix(onboarding): update the obtain login step text and add popover

### LINKED ISSUE #789: Sources: Add a source > Obtain login (OCP)
**Describe the bug**
Edits to the screen where you get your OCP login to adhere to brand standards for OpenShift, etc.

**Expected behavior**
Revised text:

Obtain your login credentials

To gather OpenShift Container Platform metering data, Cost Management requires the login token for the Operator Metering service account.

- Log in to the OpenShift Container Platform cluster with an account that has access to the Operator Metering namespace.
- To obtain your login token, run:
[command...]
- To maintain security, store the token file on a file system with limited access.

Also, please add a popover with the text shown in the linked screenshot.

**Screenshots**
https://redhat.invisionapp.com/share/XJR3A3996KR#/screens/356616236

### PR DESCRIPTION
**Pull request by boaz0**
closes #789 

//cc @dayleparker

### CODE REVIEW

File: src/pages/onboardingModal/obtainLogin/instructions.tsx [hunk 1]
```diff
@@ -1,13 +1,30 @@
...
-      <div>{t('onboarding.obtain_login.intro')}</div>
+      <div>
+        {t('onboarding.obtain_login.intro')}
+        <Popover
+          position="top"
+          bodyContent={
+            <Interpolate
+              i18nKey="onboarding.obtain_login.popover_content"
+              metering_operator={<i>metering-operator</i>}
+              learn_more={<a href="">Learn more</a>}
```
Comment (dlabrecq) [inline src/pages/onboardingModal/obtainLogin/instructions.tsx]: Can you please add a localization for "Learn More"?

**Comment by boaz0** [comment]
Thanks @dlabrecq
