### PR TITLE
fix(costmodels): Add timeout to markup validation in the wizard

### LINKED ISSUE #1106: Set a delay to the markup validation
**Describe the bug**
In the create cost model wizard, at the markup step if "-1" is typed then you will see immediately an error message saying that the value is invalid and then it will disappear. This makes the UI feel odd.

In order to fix this, adding a small delay (280 ms) on the validation may fix this.

**To Reproduce**
1. Go to 'Cost model details'
2. Click on 'Create a cost model'
3. Set AWS as type and enter a name
4. Click Next
5. Type "-1" in the text box
6. See the error

**Expected behavior**
When typing -1, there should be no error message if the value is entered fast.

### PR DESCRIPTION
**Pull request by boaz0**
closes #1106

### CODE REVIEW

File: src/pages/createCostModelWizard/markup.tsx [hunk 1]
```diff
@@ -15,51 +15,79 @@ import React from 'react';
...
+                        id="markup"
+                        name="markup"
+                        value={markup}
+                        onChange={(value: string) => {
+                          if (this.timer) {
+                            clearTimeout(this.timer);
+                          }
+                          this.timer = setTimeout(() => {
+                            this.setState({ isValid: !isNaN(Number(value)) });
+                          }, 280);
```
Comment (dlabrecq) [inline src/pages/createCostModelWizard/markup.tsx]: Using timeouts is typically frowned upon because it's not best practice. Perhaps it would be better to perform the validation via onBlur, when the user leaves the input? 

With the onChange event, validation is performed with each key press, which isn't desirable.

Comment (boaz0) [reply src/pages/createCostModelWizard/markup.tsx]: If we validate the value onChange the error message will still be shown as it does right now.
Using `onBlur` is also not perfect because if you type `minus` and focus on a different thing and then update to `-1` the error message will be shown unless you're focusing on a different element again.

Comment (dlabrecq) [reply src/pages/createCostModelWizard/markup.tsx]: If you type minus, then leave the input, it would be expected to invalid. Regardless, my point is that this should be done without a timeout

Comment (boaz0) [reply src/pages/createCostModelWizard/markup.tsx]: I see what you mean. OK - I will look at it.

Comment (boaz0) [reply src/pages/createCostModelWizard/markup.tsx]: OK - I updated the code, hope you'll like it.

**Comment by boaz0** [comment]
No problem - thanks for your time and patience
