### PR TITLE
fix(pieChart): fix legend text cut

### LINKED ISSUE #424: Charts don't fit to the table
**Describe the bug**
Charts in "Cloud Cost" tab don't fit to the table.

**To Reproduce**
1. Go to "Cloud Cost"
2. Group cost by: Account
3. Expand some entry from the table

**Screenshots**
screenshot_20190121_163114

### PR DESCRIPTION
**Pull request by boaz0**
closes #424 

Now it looks like this:
ipd2

And on mobile:
ipd1

### CODE REVIEW

**Comment by dlabrecq** [comment]
Wish you had your name on this issue as I literally submitted a PR a few minutes before you. Thought you were working on the AWS onboarding wizard flow?

File: src/components/pieChart/pieChart.tsx [hunk 1]
```diff
@@ -72,14 +73,10 @@ class PieChart extends React.Component<PieChartProps, State> {
               labels={this.getTooltipLabel}
               height={height}
               width={width}
+              // do not change chart's size on resize.
+              containerComponent={<VictoryContainer responsive={false} />}
```
Comment (dlabrecq) [inline src/components/pieChart/pieChart.tsx]: Can you use ChartContainer from PF4? Should just be a wrapper around VictoryContainer.

**Comment by boaz0** [comment]
Thanks @dlabrecq for the help. Sorry for the conflict. Next time I will see if it was assigned.
Merging in 3.. 2.. 1 :bomb: :boom:
