### PR TITLE
fix(costmodels): create cost model wizard view rates fit and finish

### LINKED ISSUE #1041: Cost models fit & finish: create cost model - price list sub step - view rates
**Describe the bug**
Fit and finish to the sub step in create cost model wizard - view rates

**Expected behavior**
- [x] Space between title-description section and table-filter part
- [x] Use "Remove" instead of "Delete" in the action button
- [x] Add pagination with 2, 4 and 6 items per page
- [x] Add search icon in the filter input

**Screenshots**
image

### PR DESCRIPTION
**Pull request by boaz0**
closes #1041

- [x] Space between title-description section and table-filter part
- [x] Use "Remove" instead of "Delete" in the action button
- [x] Add pagination with 2, 4 and 6 items per page
- [x] Add search icon in the filter input

image

### CODE REVIEW

File: src/pages/createCostModelWizard/priceListTable.tsx [hunk 1]
```diff
@@ -22,12 +26,16 @@ class PriceListTable extends React.Component<InjectedTranslateProps> {
...
+            (priceListPagination.page - 1) * priceListPagination.perPage;
+          const to = priceListPagination.page * priceListPagination.perPage;
+          const filtered = tiers.filter(iter =>
             `${iter.measurement.toLowerCase()}-${iter.metric.toLowerCase()}`.includes(
               this.state.filter.toLowerCase()
             )
           );
+          const res = filtered.slice(from, to);
           return (
             <>
```
Comment (dlabrecq) [inline src/pages/createCostModelWizard/priceListTable.tsx]: Want to add the stack component here, too?
